# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-22 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wbs',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
