# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='type',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbs',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
