# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20180625_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbs',
            name='type',
        ),
    ]
