# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_remove_wbs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='equipment_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
