# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_wbs_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
