# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20180625_1252'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.Wbs'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='definition',
            name='wbs',
            field=models.CharField(choices=[('020', '020'), ('050', '050'), ('060', '060'), ('120', '120'), ('300', '300'), ('301', '301'), ('302', '302'), ('303', '303'), ('306', '306'), ('311', '311'), ('312', '312'), ('313', '313')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
