# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20180625_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='id',
            new_name='auto_id',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='id',
            new_name='auto_id',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='type',
        ),
    ]
