# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted', models.DateField(auto_now_add=True)),
                ('attachments', models.FileField(blank=True, upload_to='attachments/')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
