# Generated by Django 2.1.2 on 2019-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190109_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='bat_lim',
            field=models.CharField(choices=[('ISBL', 'ISBL'), ('OSBL', 'OSBL')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='eq_class',
            field=models.CharField(choices=[('E', 'Heat Exchanger'), ('G', 'Pump'), ('D', 'Vessel'), ('EJ', 'Ejector')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='est_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='pfd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='pkg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='wbs',
            field=models.CharField(choices=[('020', '020 - COORDINATION'), ('050', '050 - FIELD TRIPS'), ('060', '060 - ESTIMATES'), ('120', '120 - SQUAD CHECK'), ('300', '300 - MECHANICAL SERVICES'), ('301', '301 - PUMPS'), ('302', '302 - COMPRESSORS'), ('303', '303 - FANS & BLOWERS'), ('304', '304 - CLARIFIERS and SETTLERS'), ('305', '305 - AGITATORS AND MIXERS'), ('306', '306 - FIRED EQUIPMENT'), ('307', '307 - REFRIGERATION'), ('308', '308 - LIFTING EQUIPMENT'), ('309', '309 - ATMOSPHERIC VESSELS'), ('310', '310 - WET SCRUBBERS'), ('311', '311 - HEAT EXCHANGERS'), ('312', '312 - COLUMNS and INTERNALS'), ('313', '313 - PRESSURE VESSELS'), ('314', '314 - REACTORS'), ('315', '315 - STORAGE BINS'), ('316', '316 - EVAPORATORS'), ('317', '317 - STEAM GENERATORS'), ('318', '318 - COOLING TOWERS'), ('319', '319 - STACKS'), ('320', '320 - EXTRUDERS'), ('321', '321 - CENTRIFUGES'), ('322', '322 - FILTERS & SILENCERS'), ('323', '323 - CYCLONES'), ('324', '324 - AIR POLLUTION CONTROL'), ('325', '325 - DRYERS'), ('326', '326 - CRUSHERS'), ('327', '327 - GRINDERS'), ('328', '328 - SCREENS'), ('329', '329 - BELT AND ROLLER CONVEYORS'), ('330', '330 - SCREW CONVEYORS'), ('331', '331 - BUCKET ELEVATORS'), ('332', '332 - PAN FEEDERS'), ('333', '333 - VIBRATING FEEDERS'), ('334', '334 - WEIGH SCALES'), ('335', '335 - CHUTES'), ('336', '336 - MISCELLANEOUS'), ('337', '337 - PACKAGED UNITS'), ('338', '338 - SPECIALTY VALVES'), ('339', '339 - POWER TRANSMISSION'), ('340', '340 - SEPARATORS'), ('341', '341 - COALESCERS'), ('342', '342 - AIR COOLED EXCHANGERS'), ('343', '343 - HVAC SYSTEMS'), ('344', '344 - FIRE PROTECTION'), ('345', '345 - SPECIALTY ITEMS'), ('346', '346 - PIPING COMPONENTS'), ('347', '347 - STRUCTURAL COMPONENTS'), ('348', '348 - PAINT, INSULATION, FIREPROOFING,REFRACTORY'), ('349', '349 - CHEMICALS AND LUBRICANTS'), ('350', '350 - PIPING BY MECHANICAL'), ('360', '360 - CIVIL / STRUCTURAL BY MECHANICAL'), ('370', '370 - ELECTRICAL BY MECHANICAL'), ('380', '380 - CONTROLS BY MECHANICAL'), ('390', '390 - CONSTRUCTION BY MECHANICAL')], max_length=5),
        ),
    ]
